### ISSUE TITLE
vuetify利用時においてcomponentがcenterにならない

### ISSUE THREAD

**Issue by hamachans** [16francs/gran#211]
vuetify利用時に、新しくコンポーネントを追加しcenterに寄せようとすると少しずれる

**Comment by hamachans** [comment]
```
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);

```
このように書けば解決。(cssだけだと)
他にもjqueryで書いて解決することもできるっぽい

**Comment by taba2424** [comment]
ありがと!!😊

jQueryでの変更イベントについて、Vue.jsでは検知が難しいので、cssでの実装にしよ!!

> https://vuejsdevelopers.com/2017/05/20/vue-js-safely-jquery-plugin/
